### ISSUE TITLE
Check elevated access

### ISSUE THREAD

**Issue by tron2k** [Microsoft/ExPerfWiz#2]
Hello,
first thanks for your nice script.

Why do you make this check in the function IsAdmin? 
`if ($Windows2008R2  -and !$IsAdmin)`
This condition can never be true because you set this variables

```
$script:Windows2003 = $false
$script:Windows2008 = $false
$script:Windows2008R2 = $false
$script:Windows2012 = $false
$script:Windows2012R2 = $false
$script:Windows2016 = $false
$script:Windows2019 = $false
```

Or do i miss something?

best wishes

**Comment by Canthv0** [comment]
Total Code rewrite
New version is based on PowerShell modules and doesn't check for isadmin any more
