### ISSUE TITLE
Loop max files size on failure

### ISSUE THREAD

**Issue by dpaulson45** [Microsoft/ExPerfWiz#20]
Sometimes for whatever reason, we get errors when trying to set max file size to 4096 or a different number on different machines for different reasons. Logic should be put in place to attempt to change the max file size by increasing it by one on start if we get an error. 

```
   

PS E:\ExPerfWiz> New-ExPerfwiz -Name Exchange_perfwiz -MaxSize 4096 -FolderPath E:\ExPerfWiz -Circular


Please choose a Template:
1> Exch_10_Full.xml
2> Exch_13_16_19_Full.xml


Choose Template (1-2): 2


Name Status Schedules OutputPath
---- ------ --------- ----------
Exchange_perfwiz Stopped Off E:\ExPerfWiz\ServerName_2_Exchange_perfwiz



PS E:\ExPerfWiz> Start-ExPerfwiz -Name Exchange_perfwiz
Error: Unable to create the specified log file.
At E:\ExPerfWiz\Start-ExPerfwiz.ps1:55 char:9
+ Throw $logman
+ ~~~~~~~~~~~~~
+ CategoryInfo : OperationStopped: ( Error: Unable ...ified log file.:String) [], RuntimeException
+ FullyQualifiedErrorId : Error: Unable to create the specified log file.

```

Changed the value to 4095 and it worked, as we can't go up for script limitations

**Comment by Canthv0** [comment]
Implemented something that should resolve this.
A warning will be logged and it will try 4 times to fix this by stepping up the size.  Please let me know if there are any further failures as I was not able to test this.

**Comment by dpaulson45** [comment]
@Canthv0 you should link either your PR or your commit to the issue so that way it is easier to find what you did to resolve issues.
