### ISSUE TITLE
`logman import` fails when System GI and User GI differ. `(Get-Date ...).tostring()`

### ISSUE THREAD

**Issue by filimonic** [Microsoft/ExPerfWiz#23]
`logman import` fails when System globalization information and User GI differ, because of `(Get-Date ...).tostring()` uses executing user's locale, and logmain import seems to be using system's globalization information.

In case when user's locale set to Russian and system locale set to English (US), logman expects dates in XML in `d/m/yyyy` format, but gets `dd.mm.yyyy` instead and fails with Type Mismatch.

**Comment by Canthv0** [comment]
Get all get-date formats into invariant formats
this should now work regardless of culture
